"""
Script to take a list of abstracts and dump them into a new directory.
The new directory will be created in the parent directory specified 
by the user, with a name specified by the user. 

Author: Serena G. Lotreck
"""
from os.path import abspath 
from os.path import exists
from os import listdir
from os import makedirs
from shutil import move

import argparse 
import pandas as pd


def main(abstract_list, abstract_dir, parent_dir, new_dir_name):

    print('\n======> Putting chosen abstracts into new directory <======\n')

    # Read in the abstract list
    print('\nReading in data...')
    abs_df = pd.read_csv(abstract_list)
    print('Snapshot of abstract list:\n')
    print(abs_df.head())

    # Make new dir
    print('\nMaking new directory...')
    dir_name = f'{parent_dir}/{new_dir_name}'
    assert not exists(dir_name), (f'{dir_name} already exists, '
                                'please choose another name.')
    makedirs(dir_name)
    print(f'New directory {dir_name} has been created')

    # Move files if they are in the abstract list
    print('\nMoving relevant files to new directory...')
    for f in listdir(abstract_dir):
        if abs_df['abstract_name'].str.contains(f).any():
            move(f'{abstract_dir}/{f}', dir_name)

    print('Files have been moved!')
    print('Snapshot of files in the new directory:')
    if len(listdir(dir_name)) > 5:
        print(listdir(dir_name)[:5])
    else:
        print(listdir(dir_name))

    print('\nDone!\n')

if __name__ == '__main__':

    parser = argparse.ArgumentParser(description='Put chosen abstracts '
                                        'in a new directory')

    parser.add_argument('-abstract_list', type=str,
            help='Path to csv generated by cluster_docs.py')
    parser.add_argument('-abstract_dir', type=str,
            help='Path to directory where all abstracts are stored')
    parser.add_argument('-parent_dir', type=str, 
            help='Path to directory where the new directory should be placed')
    parser.add_argument('-new_dir_name', type=str, 
            help='Name for new directory')
    

    args = parser.parse_args()

    args.abstract_list = abspath(args.abstract_list)
    args.abstract_dir  = abspath(args.abstract_dir)
    args.parent_dir    = abspath(args.parent_dir)

    main(args.abstract_list, args.abstract_dir, args.parent_dir, 
            args.new_dir_name)
